#pragma once

/**
 * Fixture access for the engine's tests.
 *
 * The fixtures in `engine/testdata/` are generated by the TypeScript reference
 * engine (`npm run export:golden`) and are never edited by hand. Tests read them
 * as bytes and parse them with the same insertion-order-preserving parser the
 * library uses, so key order survives into the assertions.
 */

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

#include <agri/canonical_json.hpp>
#include <agri/error.hpp>

#ifndef AGRI_TESTDATA_DIR
#error "AGRI_TESTDATA_DIR must be set by the build to the absolute path of engine/testdata"
#endif

namespace agri::test {

inline const std::filesystem::path& testdataDir() {
  static const std::filesystem::path directory(AGRI_TESTDATA_DIR);
  return directory;
}

inline std::filesystem::path fixturePath(std::string_view relative) {
  return testdataDir() / std::filesystem::path(relative);
}

inline std::string readFixtureText(std::string_view relative) {
  std::ifstream stream(fixturePath(relative), std::ios::binary);
  if (!stream) {
    throw AgriEngineError("E_MISSION_INPUT",
                          "cannot read fixture: " + std::string(relative));
  }
  std::ostringstream buffer;
  buffer << stream.rdbuf();
  return buffer.str();
}

inline Json readFixture(std::string_view relative) { return parseJson(readFixtureText(relative)); }

/** File names directly under `directory`, sorted, so test order is stable. */
inline std::vector<std::string> fixtureNames(std::string_view directory) {
  std::vector<std::string> names;
  for (const auto& entry :
       std::filesystem::directory_iterator(testdataDir() / std::filesystem::path(directory))) {
    if (entry.is_regular_file()) {
      names.push_back(entry.path().filename().string());
    }
  }
  std::sort(names.begin(), names.end());
  return names;
}

} // namespace agri::test
